### ISSUE TITLE
the masonry view is blank when i add data to state.data

### ISSUE THREAD

**Issue by chienvu123** [brh55/react-native-masonry#103]
i use Example at lib, when i click push new data, view is removed

anyone help me, please!

---------
i use version 0.5.0

**Comment by trungnt85** [comment]
same problem here, since I tried to load next page when grid end reached

**Comment by DanthonyPabon** [comment]
@logicallyDimp it's not working for me
```
 if (this.state.loading) {
      return (
        <View style={styles.ClusterListBoxEmpty}>
          <ActivityIndicator animating={true} color="#242424" size="large" />
          <Text style={styles.textTitleEmpty}>
            Aquí aparecerán las fotos y videos que tomes con Picnow
          </Text>
        </View>
      );
    }
    if (Object.keys(this.state.ClusterAll).length === 0) {
      return (
        <View style={styles.ClusterListBoxEmpty}>
          <Text style={styles.textTitleEmpty}>No has tomado ninguna foto.</Text>
        </View>
      );
    } else if (Object.keys(this.state.ClusterAll).length > 0) {
      let uri = [];
      this.state.ClusterAll.map(({ view }) => {
        uri.push({ uri: view });
      });
      console.log(uri);
      return (
        <View style={styles.ClusterListBox}>
          <Masonry
            sorted
            columns={3} // optional - Default: 2
            bricks={uri}
          />
        </View>
      );
    }
```

**Comment by logicallyDimp** [comment]
have you tried doing it like this?
```js
if(this.state.loading) {
	return (
		<View style={styles.ClusterListBoxEmpty}>
			<ActivityIndicator animating={true} color="#242424" size="large" />
			<Text style={styles.textTitleEmpty}>
				Aquí aparecerán las fotos y videos que tomes con Picnow
			</Text>
		</View>
	);
}
else {
	if (Object.keys(this.state.ClusterAll).length === 0) {
		return (
			<View style={styles.ClusterListBoxEmpty}>
				<Text style={styles.textTitleEmpty}>No has tomado ninguna foto.</Text>
			</View>
		);
	} else if (Object.keys(this.state.ClusterAll).length > 0) {
		let uri = [];
		this.state.ClusterAll.map(({ view }) => {
			uri.push({ uri: view });
		});
		console.log(uri);
		return (
			<View style={styles.ClusterListBox}>
				<Masonry
					sorted
					columns={3} // optional - Default: 2
					bricks={uri}
				/>
			</View>
		);
	}
}
```

**Comment by Richi2293** [comment]
same thing for me, have you solved it?

**Comment by DanthonyPabon** [comment]
I don't using it

**Comment by brh55** [comment]
So I looked into this issue a while back, it really stems from an async call to load the image, but doesn't complete before the masonry view changes. This causes the masonry to run into a runtime exception and stops loading completely. If anyone wants to try to fix this to integrate cancellable async calls, this should fix the issue (almost certain).

**Comment by Abdelrahman-Nabil** [comment]
I still encounter the same issue when appending new data to the list, anyone has a quick fix to it ?
