### ISSUE TITLE
All images are not rendered at once.

### ISSUE THREAD

**Issue by priyankverma** [brh55/react-native-masonry#55]
Number of columns is 2, only one side of the images are rendered sometimes, re-rendering the component fixes the issue for some while, please provide a better solution.

**Comment by srameshr** [comment]
Same here!

**Comment by brh55** [comment]
Anyway we can duplicate this configuration. Access to the codebase or a sample codebase that replicates this bug would be greatly appreciated.

**Comment by srameshr** [comment]
@brh55 https://github.com/brh55/react-native-masonry/issues/41 This is what the issue is and the component code for that is mentioned in the issue.

**Comment by priyankverma** [comment]
I tried using setTimeout for resetting the contents in the state, it worked for some time, but isn't the permanent solution to the problem.

**Comment by vvavepacket** [comment]
I encounter this issue on iOS and android as well

**Comment by srameshr** [comment]
@priyankverma @vvavepacket I tried it with ```0.4.4``` and it works fine.

**Comment by brh55** [comment]
The newest version should fix this issue now, if not please update react-navigation and seeing if that fixes it before re-opening a new issue 😄

**Comment by srameshr** [comment]
@brh55 It's ```react-native-navigation``` I have not tried ```react-navigation```

**Comment by brh55** [comment]
@srameshr Ahh I see, I have not messed with R-N-N before.

**Comment by vvavepacket** [comment]
Hi, I have updated to 0.4.4, but still I could see missing images. I am also not using react-native-navigation

![image](https://user-images.githubusercontent.com/8295642/34183204-95b53664-e4e7-11e7-96ec-f2142a4efe64.png)

**Comment by Gerharddc** [comment]
I am still getting this with 0.4.4 and the latest react-navigation.

**Comment by vvavepacket** [comment]
@Gerharddc  are your images local or fetching from the internet?

**Comment by Gerharddc** [comment]
@vvavepacket I am using internet images

**Comment by Gerharddc** [comment]
If it makes a difference, the masonry component is inside a tab.

**Comment by brh55** [comment]
@Gerharddc which version of RN, React, and which navigator are you using.

**Comment by Gerharddc** [comment]
@brh55  I have RN 0.51.0, React 16.0.0 and react-navigation 1.0.0-beta.22

**Comment by vvavepacket** [comment]
@Gerharddc 

Were you able to solve your problem? I am encountering the same thing when masonry is inside a tab
